import Head from 'next/head'

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="icon"
          href="https://nextjs.org/favicon.ico"
          type="image/png"
        />
      </Head>
      <body>{children}</body>
    </html>
  );
}
